"""FRMR-compatible attestation artifact — the v1 Phase 2 primary output.

`AttestationArtifact` is the shape Efterlev serializes to disk for
downstream consumption (3PAO review, RegScale OSCAL-Hub ingestion v1.5+,
CSP package assembly). It is structurally inspired by the FRMR
documentation format — theme-keyed KSI indicators, top-level `info` block,
canonical JSON — but carries attestation data rather than catalog data, so
it is not a valid FRMR documentation file and is not validated against
`catalogs/frmr/FedRAMP.schema.json`. That schema describes the FRMR
catalog; FedRAMP has not published an attestation-output schema as of
April 2026. See DECISIONS 2026-04-22 "Phase 2: FRMR attestation generator"
for the schema-posture design call.

Validation: Pydantic enforces structure at construction time with
`extra="forbid"` and strict literal types. A malformed artifact raises
`ValidationError` before the generator returns. An external JSON Schema
mirror is a follow-up (`catalogs/efterlev/efterlev-attestation.schema.json`)
for consumers who want to validate the serialized file without a Python
dependency.

Trust posture: the artifact always carries a `provenance.requires_review`
flag and a `review_banner` string in the serialized output — the draft-not-
authorization commitment from CLAUDE.md Principle 7 is visible in every
emitted file.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from efterlev.models.attestation_draft import (
    AttestationCitation,
    AttestationMode,
    AttestationStatus,
)

ArtifactTool = Literal["efterlev"]


class AttestationArtifactInfo(BaseModel):
    """Top-level metadata block. Mirrors FRMR's `info` shape."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    tool: ArtifactTool = "efterlev"
    tool_version: str
    baseline: str
    frmr_version: str
    frmr_last_updated: str
    generated_at: datetime
    scope: str = (
        "KSI-level attestation draft. NOT a FedRAMP authorization, NOT a 3PAO "
        "assessment. Every narrative entry requires human review before "
        "submission. See `provenance.review_banner` below."
    )


class AttestationArtifactIndicator(BaseModel):
    """Per-indicator attestation record inside the artifact.

    Fields parallel `AttestationDraft` plus `controls` (the 800-53 control
    list resolved from FRMR) and `claim_record_id` (if the agent persisted
    a provenance record for this draft). Readers diffing the artifact
    against the FRMR catalog can align by indicator id; readers walking
    provenance can follow `claim_record_id` back to the narrative Claim.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    mode: AttestationMode
    status: AttestationStatus | None = None
    narrative: str | None = None
    citations: list[AttestationCitation] = Field(default_factory=list)
    controls: list[str] = Field(default_factory=list)
    claim_record_id: str | None = None


class AttestationArtifactTheme(BaseModel):
    """FRMR-shaped theme container: `{indicators: {KSI-ID: indicator-record}}`."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    indicators: dict[str, AttestationArtifactIndicator] = Field(default_factory=dict)


class AttestationArtifactProvenance(BaseModel):
    """Draft-posture commitment carried in every emitted artifact.

    `requires_review=True` is a hard invariant at v1: Efterlev never
    produces a "final, no-review-needed" attestation. When the Phase 5
    review-workflow landing sets `reviewed_by` and `approved_by`, THIS
    flag stays true — the review-trail fields are additive; the requires-
    review guarantee is what the tool promises, not what a reviewer
    promises about their own work.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    requires_review: Literal[True] = True
    review_banner: str = (
        "DRAFT — requires human review. Generated by Efterlev from detector "
        "evidence and human-authored Evidence Manifests. Not a FedRAMP "
        "authorization; not a 3PAO assessment. A qualified reviewer must "
        "validate every narrative and citation before this artifact is "
        "submitted to any authorizing body."
    )


class AttestationArtifact(BaseModel):
    """Complete FRMR-compatible attestation artifact.

    Top-level keys chosen to parallel FRMR documentation: `info` block,
    `KSI` keyed by theme short_name. The `provenance` block is our
    addition (FRMR's catalog has no equivalent — the CSP-attestation
    story is what Efterlev produces and FRMR does not).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    info: AttestationArtifactInfo
    KSI: dict[str, AttestationArtifactTheme] = Field(default_factory=dict)
    provenance: AttestationArtifactProvenance = Field(
        default_factory=lambda: AttestationArtifactProvenance()
    )

    @property
    def indicator_count(self) -> int:
        """Total number of indicators across all themes in this artifact."""
        return sum(len(theme.indicators) for theme in self.KSI.values())
